### ISSUE TITLE
Docs changes

### ISSUE THREAD

**Issue by rishabh1jain** [CiscoZeus/python-zeusclient#2]
Please, in the doc, 

1.Mark which parameters are mandatory to pass and which are optional (plus their default actions). FOR BOTH LOGS AND METRICS
2. Mention Timestamp precision
3. Change z.getMetricNames(metric_name="<METRIC_NAME>", limit=10) to  z.getMetricNames() in the doc

**Comment by marcsolanas** [comment]
Thanks!
