### ISSUE TITLE
vague total

### ISSUE THREAD

**Issue by rishabh1jain** [CiscoZeus/python-zeusclient#3]
Sample Response:
(200, {u'total': 24, u'result': [{u'timestamp': 1433484292, u'message': u'My Test Log'}, {u'timestamp': 1433484328, u'message': u'My Test Log'}, {u'timestamp': 1433484000, u'message': u'Rishabh'}, {u'timestamp': 1433484000, u'message': u'//////////////////////'}, {u'timestamp': 1433484001, u'message': u'/11111212131242353455123456789'}, {u'timestamp': 1433484000, u'message': u'//////////////////////'}, {u'timestamp': 1433484328, u'message': u'My Second Test Log'}, {u'timestamp': 1433484292, u'message': u'My Second Test Log'}, {u'timestamp': 1433484000, u'message': u'Rishabh'}, {u'timestamp': 1433484000, u'message': u'My Test Log'}]})

It says total is 24, and sent me 10 elements. Name "total" seems vague.

**Comment by rishabh1jain** [comment]
very trivial. should be good to update the docs about meaning.

**Comment by johnugeorge** [comment]
It is same issue as #8

**Comment by marcsolanas** [comment]
Actually, the "total" is still there. Also need to add a comment on that.
