### ISSUE TITLE
Count mismatch

### ISSUE THREAD

**Issue by amsaha** [CiscoZeus/python-zeusclient#5]
I have the following very simple code (right out of the documentation at https://cisco-zeus.readthedocs.org/en/latest/usage.html). This code puts into two log entries and retrieves all log entries till "now". I would expect that the number of entries retrieved should keep on increasing by two everytime I run this command (since two new entries are first inserted):

``` python
from zeus import client
import pprint

z = client.ZeusClient('a7b71e4b', 'api.ciscozeus.io')
pprint.pprint(z)

logs = [
    {"message": "My Test Log"},
    {"message": "My Second Test Log"}
]
result = z.sendLog('AMISAHA',logs)
pprint.pprint(result)

result = z.getLog('AMISAHA', pattern='*', limit=10)
pprint.pprint(result)
```

However, I see that there are instances when an odd number of messages are returned. Is this expected due to some delay I guess since the code inserts and immediately retrieves?

```
<zeus.client.ZeusClient instance at 0x7f3afec37cf8>
(200, {u'successful': 2})
(200,
 {u'result': [{u'message': u'My Test Log', u'timestamp': 1433486412},
              {u'message': u'My Test Log', u'timestamp': 1433486074},
              {u'message': u'My Second Test Log', u'timestamp': 1433486395},
              {u'message': u'My Second Test Log', u'timestamp': 1433486074},
              {u'message': u'My Test Log', u'timestamp': 1433486395},
              {u'message': u'My Second Test Log', u'timestamp': 1433486433},
              {u'message': u'My Second Test Log', u'timestamp': 1433486412}],
  u'total': 7})
```

**Comment by amsaha** [comment]
Apparently, there is some delay for the logs to make it into the system. Hence, the mismatch I presume. 

Maybe we should document this behavior.

**Comment by johnugeorge** [comment]
there should be delay before retrieving the posted metrics. I think, that is acceptable for any system.  In my tests, I had put 2 sec delay between Post and Get reqs.

**Comment by marcsolanas** [comment]
What Johnu says is True. I'll add it to the docs.
In the python example code, I require the user input after inserting data, before retrieving it, so the data has time to be processed.
