### ISSUE TITLE
Bad example in documentation for metrics

### ISSUE THREAD

**Issue by rishabh1jain** [CiscoZeus/python-zeusclient#7]
Even if i copy paste things given in documentation,

metrics = [{"timestamp": 123541423, "value": 0},
           {"timestamp": 123541424, "value": 1},
           {"timestamp": 123541425, "value": 2.0}
]

print z.sendMetric("rishabh",metrics)

it print s (400, {u'successful': 0, u'error': u'invalid input'})

**Comment by xyhuang** [comment]
seems the input has to be in the following format instead of what specified in the document,
[{"timestamp": <value>, "point": {<key>: <value>}}]

**Comment by travelist** [comment]
probably even without timestamp, like [{"point": {"col": 1, ...}}], it works.
We can confirm via http://api.ciscozeus.io/

**Comment by marcsolanas** [comment]
Ohhh true. I forgot to change this. Well spotted!!
