### ISSUE TITLE
getLog returns just 10 entries even when "limit is not specified"

### ISSUE THREAD

**Issue by amsaha** [CiscoZeus/python-zeusclient#8]
I believe this is by design but needs to be documented.

**Comment by johnugeorge** [comment]
I saw the same issue. Default value of limit is 10. It has to be specified in the docs

**Comment by marcsolanas** [comment]
True. This is set in the API.

**Comment by marcsolanas** [comment]
Changed it in the API. Also added a note in the API docs.
